{
  imports = [
    ./software.nix
    ./ghostty.nix
    ./firefox.nix
    ./waybar.nix
    ./waybar-style.nix
    ./dunst.nix
    ./rofi.nix
    ./fastfetch.nix
    ./fish.nix
    ./direnv.nix
    ./git.nix
    ./opencode.nix
    ./mcp.nix
    ./codex.nix
    ../niri/niri.nix
    ./input-method.nix
    ./yazi.nix
    ./wallpaper.nix
  ];
}
